version: '2'

services:
    consul:
      image: progrium/consul
      command: -server -bootstrap -advertise 192.168.99.100 -node 192.168.99.100 -log-level debug -ui-dir /ui
      ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"