version: '2'

services:
  zookeeper:
    image: mesoscloud/zookeeper:3.4.8-centos-7
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      SERVERS: 'server.1=127.0.0.1'
      MYID: '1'

  mesosmaster:
    image: mesoscloud/mesos-master:0.28.1-centos-7
    ports:
      - "5050:5050"
    environment:
      MESOS_ZK: 'zk://zookeeper:2181/mesos'
      MESOS_QUORUM: '1'
      MESOS_CLUSTER: 'local'
      MESOS_HOSTNAME: ${DOCKER_HOST_IP}
      MESOS_ADVERTISE_IP: ${DOCKER_HOST_IP}
      MESOS_LOG_DIR: '/var/log/mesos/master' 

  mesosslave1:
    image: mesoscloud/mesos-slave:0.28.1-centos-7
    ports:
      - "5051:5051"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/local/bin/docker:/usr/bin/docker
    environment:
      MESOS_MASTER: 'zk://zookeeper:2181/mesos'
      MESOS_PORT: '5051'
      MESOS_LOG_DIR: '/var/log/mesos/slave'
      MESOS_CONTAINERIZERS: 'docker,mesos'
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
      MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
      MESOS_DOCKER_STOP_TIMEOUT: '60secs'
      MESOS_PORT: 5051
      MESOS_HOSTNAME: ${DOCKER_HOST_IP}
      MESOS_ADVERTISE_IP: ${DOCKER_HOST_IP}
      # MESOS_DEFAULT_ROLE: '*'

  mesosslave2:
    image: mesoscloud/mesos-slave:0.28.1-centos-7
    ports:
      - "5052:5052"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/local/bin/docker:/usr/bin/docker
    environment:
      MESOS_MASTER: 'zk://zookeeper:2181/mesos'
      MESOS_PORT: '5051'
      MESOS_LOG_DIR: '/var/log/mesos/slave'
      MESOS_CONTAINERIZERS: 'docker,mesos'
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
      MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
      MESOS_DOCKER_STOP_TIMEOUT: '60secs'
      MESOS_PORT: 5052
      MESOS_HOSTNAME: ${DOCKER_HOST_IP}
      MESOS_ADVERTISE_IP: ${DOCKER_HOST_IP}
      # MESOS_DEFAULT_ROLE: 'persistent-volumes'

  marathon:
    image: mesoscloud/marathon:1.1.1-centos-7
    ports:
      - "8080:8080"
    environment:
      MARATHON_HOSTNAME: ${DOCKER_HOST_IP}
      MARATHON_ZK: 'zk://zookeeper:2181/marathon'
      MARATHON_MASTER: 'zk://zookeeper:2181/mesos'
      MARATHON_EVENT_SUBSCRIBER: 'http_callback'
      MARATHON_TASK_LAUNCH_TIMEOUT: '300000'
      # MARATHON_MESOS_ROLE: 'persistent-volumes'

  weavescope:
    image: weaveworks/scope:0.13.1
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"