# traefik.toml

port = ":80"
graceTimeOut = 10
logLevel = "DEBUG"

[web]
address = ":8080"

[marathon]
endpoint = "http://marathon:8080"
# interface = "eth0"
watch = true
domain = "marathon.localhost"

# [consul]
# endpoint = "consul:8500"
# watch = true
# prefix = "traefik"